title: "Hospital 990 Schedule H Data"
author: "Blog Author"
description: "Really cool blog about ..."

# Jekyll settings
permalink: /:title/          # see https://jekyllrb.com/docs/permalinks/
paginate: 2                  # number of articles per page, remove to disable pagination
excerpt_separator: "\n\n\n"  # indicates the end of the excerpt by two blank lines

# Theme settings
show_excerpts: false         # show article previews on the home page instead of headlines
date_format: "%B %d, %Y"     # see http://shopify.github.io/liquid/filters/date/
dark_theme: false            # enables dark mode
dark_header: true            # uses dark header whether dark_theme is enabled or not
minimal_theme: false         # radically minimalistic theme

navigation:                  # show navigation links in the header	
  - index.md
  - data.md  
  - health-data.md
  - lit-review.md
  - resources.md
  - about.md



icons:                       # show icons in the header, for all possible icons see http://fontawesome.io/icons/
  # envelope: "mailto:niklasbuschmann@users.noreply.github.com"
  github: "https://github.com/lecy/irs-990-schedule-h/edit/master/docs/"
  
  
  
comments:                    # embed disqus or isso comments
#  disqus: "disqus-contrast"
#  isso: "comments.mysite.org"

remote_theme: niklasbuschmann/contrast

plugins: 
 - jekyll-remote-theme
 - jekyll-feed
 - jekyll-paginate
 - jekyll-default-layout


